version: "3.8"

services:

  # Database:
  mysql-service:

    # Image name:
    image: eitanlander/libre-voyage-mysql:1.0

    # Dockerfile location:
    build: ./Database

    # Container name:
    container_name: libre-voyage-mysql

    # Port binding:
    ports:
      - 3306:3306
    
    # On crach - Restart (unless stopped manually):
    restart: unless-stopped

    # Required env variables for the initial installation:
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: Eitan
      MYSQL_PASSWORD: LibreVoyage
      MYSQL_DATABASE: libre-voyage
      MYSQL_ROOT_PASSWORD: LibreVoyage
          
   # Volume:
    volumes:
      - libre-voyage:/var/lib/mysql

  # REST API:
  api-service:

    # Service depend on:
    depends_on:
      - mysql-service

    # Image name:
    image: eitanlander/libre-voyage-api:1.0

    # Dockerfile location:
    build: ./Backend

    # Container name:
    container_name: libre-voyage-api

    # Port binding:
    ports:
      - 4000:4000

    # On crach - Restart (unless stopped manually):
    restart: unless-stopped     

    # Required env variables for the initial installation:
    environment:
      MYSQL_HOST: mysql-service # Computer network name.
      MYSQL_USER: Eitan
      MYSQL_PASSWORD: LibreVoyage
      MYSQL_DATABASE: libre-voyage # Optinal (already on the .env file).

 # Frontend:
  react-service:

    # Service depend on:
    depends_on:
      - api-service

    # Image name:
    image: eitanlander/libre-voyage-react:1.0

    # Dockerfile location:
    build: ./Frontend

    # Container name:
    container_name: libre-voyage-react

    # Port binding:
    ports:
      - 80:3000

    # On crach - Restart (unless stopped manually):
    restart: unless-stopped  

# Volume list:
volumes:
  libre-voyage: